### PR TITLE
Prepare release 1.5.0

### PR DESCRIPTION
**Pull request by dblenkus**
@tjanez please merge #303 before the release.
@kostko Do we wait for #306? When will it be ready?

### CODE REVIEW

**Comment by mstajdohar** [comment]
I suggest to include https://github.com/genialis/resolwe/pull/306 in the next release, because it is a breaking change.

**Comment by kostko** [comment]
> When will it be ready?

The major thing is fixing all issues in resolwe-bio. I would like to do that before we merge that one as otherwise everything will break once merged.

**Comment by tjanez** [comment]
> @tjanez please merge #303 before the release.

Done

**Comment by tjanez** [comment]
> I suggest to include #306 in the next release, because it is a breaking change.

I agree.

**Pull request merged**
