### PR TITLE
Move date, datetime, file and dir types to no choices list

### PR DESCRIPTION
**Pull request by hadalin**

### CODE REVIEW

**Comment by hadalin** [comment]
Also moved date and datetime to no choices list.

**Comment by hadalin** [comment]
Also added [number](https://github.com/genialis/resolwe/pull/277/files#diff-4f75b3ca0f637c172c88b914e3e2f861R149) to choices.

**Comment by mstajdohar** [comment]
Rebase please

**Comment by mstajdohar** [comment]
Please rebase

**Pull request merged**
