### PR TITLE
Add support for building only specific indexes

### PR DESCRIPTION
**Pull request by kostko**

### CODE REVIEW

**Comment by mstajdohar** [comment]
Please merge after #203.

**Comment by mstajdohar** [comment]
I was working on isolating the Elasticsearch indexes in tests. See https://github.com/genialis/resolwe/pull/208

**Comment by mstajdohar** [comment]
Please rebase on to master and support the new testing framework.

**Comment by dblenkus** [comment]
@kostko can you add an option to skip some indexes?

**Comment by kostko** [comment]
There is now support for `--exclude`, which may be specified multiple times (`--index` also).

**Comment by dblenkus** [comment]
Looks OK

**Pull request merged**
