### PR TITLE
Add view to check if slug exists

### PR DESCRIPTION
**Pull request by dblenkus**

### CODE REVIEW

**Comment by kostko** [comment]
> Maybe `slug_exists` route name would better describe what this method does?

Yeah, I agree with @hadalin on this, otherwise the pull request looks good to me.

**Comment by dblenkus** [comment]
Renamed

**Comment by hadalin** [comment]
I think [this line](https://github.com/genialis/genesis-platform/blob/master/requirements.txt#L2) should also be updated upon Resolwe update.

**Comment by kostko** [comment]
It has already been updated ;-)

**Pull request merged**
