### PR TITLE
Track dependencies between Data objects

### PR DESCRIPTION
**Pull request by kostko**

### CODE REVIEW

**Comment by kostko** [comment]
Why did Travis not run tests for this PR?

**Comment by dblenkus** [comment]
cc @tjanez

**Comment by dblenkus** [comment]
Maybe split test in to two, as the first and the second part are completely independent. Otherwise LGTM.

**Comment by kostko** [comment]
What are these linter failures on Travis?
```
resolwe/flow/models.py:399: [E1101(no-member), Data.save_dependencies.add_dependency] Instance of 'ManyToManyField' has no 'add' member
resolwe/flow/models.py:462: [E1101(no-member), Data.save] Instance of 'ForeignKey' has no 'input_schema' member
```

**Comment by kostko** [comment]
Ah I see, we need to add `# pylint: disable=no-member` everywhere.

**Pull request merged**
