### PR TITLE
Add data permissions test

### PR DESCRIPTION
**Pull request by hadalin**
This PR adds a unit test that causes `500` error: `DoesNotExist: Permission matching query does not exist.`:

```
Error
Traceback (most recent call last):
  File "projects/genialis/resolwe/resolwe/permissions/tests/test_permissions.py", line 237, in test_user_with_share
    resp = self._detail_permissions(self.data.pk, data, self.user1)
  File "projects/genialis/resolwe/resolwe/test/testcases/api.py", line 238, in _detail_permissions
    return self.detail_view(request, pk=pk)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "projects/genialis/resolwe/resolwe/permissions/mixins.py", line 67, in detail_permissions
    update_permission(obj, payload)
  File "projects/genialis/resolwe/resolwe/permissions/utils.py", line 112, in update_permission
    set_permissions('users', 'add')
  File "projects/genialis/resolwe/resolwe/permissions/utils.py", line 110, in set_permissions
    perm_func('{}_{}'.format(perm.lower(), content_type), entity, obj)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/guardian/shortcuts.py", line 105, in assign_perm
    return model.objects.assign_perm(perm, user, obj)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/guardian/managers.py", line 39, in assign_perm
    permission = Permission.objects.get(content_type=ctype, codename=perm)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File ".virtualenvs/resolwe/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Permission matching query does not exist.
```

### CODE REVIEW

**Comment by mstajdohar** [comment]
+1 for the test @hadalin!

**Comment by mstajdohar** [comment]
We need to support a better response for non-existing permissions. @dblenkus Please generalize the test to other non exiting permissions like `foo` and `bar`.

**Comment by mstajdohar** [comment]
@kostko What status code would you suggest, 40?

**Comment by kostko** [comment]
Yes, it should be 400 (Bad request) with the output saying that the given permission does not exist.

**Comment by dblenkus** [comment]
This is a known problem, but doesn't have a high priority, as permissions are normally auto-generated, so user cannot directly influence them. It should return 400 Bad request response.

Also I think that it would be more appropriate to write issues for such reports instead of creating pull requests.

**Comment by mstajdohar** [comment]
> Also I think that it would be more appropriate to write issues for such reports instead of creating pull requests.

Or at least create both.

@hadalin Please create a bug report please and reference this PR.

**Comment by dblenkus** [comment]
Closed in favour of #328.

**Pull request closed without merging**
