### PR TITLE
Add `dirname` and `relative_path` Jinja filters

### PR DESCRIPTION
**Pull request by JureZmrzlikar**

### CODE REVIEW

**Comment by mstajdohar** [comment]
Is it unhydrate or dehydrate? Ha ha :)

**Comment by JureZmrzlikar** [comment]
@dblenkus , thanks for the hint, it helped a lot!
@mstajdohar Nice suggestion, i renamed filter to `get_dehydrated_path`.
Please have another review pass.

**Comment by JureZmrzlikar** [comment]
After spending some time on this, i've found a solution that works without adding a custom filter to Resolwe. Will set this as WIP until we decide what exactly do we want to do.

**Comment by JureZmrzlikar** [comment]
I found a different solution, but decided to keep the PR. @dblenkus @mstajdohar please review again.

**Pull request merged**
