### PR TITLE
Add missing re-import dependencies to resolwe/base

### PR DESCRIPTION
**Pull request by kostko**

### CODE REVIEW

**Comment by mstajdohar** [comment]
Should you a more thorough cleanup, e.g.:
```
    apt-get autoremove --purge -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip && \
    rm -rf /tmp/*
```

**Comment by kostko** [comment]
Yes, I didn't look at cleanup but we can add it so it is similar as in `resolwebio/base`.

**Comment by kostko** [comment]
Added. The `autoremove` is not needed here as we don't actually remove any build-only packages.

**Comment by kostko** [comment]
Hm, actually this image should also install all the decompression utilities referenced in `re-import` as otherwise unpacking may still fail?

**Comment by mstajdohar** [comment]
Yes, thanks for spotting this.

**Pull request merged**
